name: CI App
on:
  push
concurrency: ci-app-${{ github.ref }}
jobs:

 build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

      
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    
    - name: Compile Gradle
      run: |
        chmod +x gradlew
        ./gradlew clean build 

    - name: Run SonarCloud Analysis
      run: |
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL:"https://sonarcloud.io/"
